---
admin_user: martial

# Where you want Docker to store its container data.
docker_home: /tank/docker

# Where you want Docker to store images
docker_image_directory: "/docker/data"

# Docker storage driver https://docs.docker.com/storage/storagedriver/select-storage-driver/#supported-backing-filesystems
# aufs over zfs driver, as it allow me to bind each container to a separate zfs dataset and monitor them using zfs list ( print the container's name instead of random chars)
# docker_storage_driver: aufs
# "storage-driver": "{{ docker_storage_driver }}"
# docker_storage_driver: zfs
