---
- name: Get docker group id
  group:
    name: docker
  register: docker_group

- name: Create filesystem for Netdata
  community.general.zfs:
    name: "{{ netdata_volume }}"
    state: present
    extra_zfs_properties:
      mountpoint: "{{ netdata_mountpoint }}"

- name: Netdata Docker Container
  docker_container:
    name: netdata
    hostname: "{{ server_hostname }}.{{ server_domain }}"
    networks:
      - name: "{{ custom_network_name }}"
        aliases:
          - netdata
    network_mode: "{{ custom_network_name }}"
    networks_cli_compatible: yes
    image: netdata/netdata
    state: started
    pull: true
    ports:
      - "{{ netdata_port }}:19999"
    volumes:
      - "/proc:/host/proc:ro"
      - "/sys:/host/sys:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    env:
      PGID: "{{ docker_group.gid }}"
    capabilities:
      - SYS_PTRACE
    security_opts:
      - apparmor:unconfined
    restart_policy: unless-stopped
    memory: "{{ netdata_memory }}"
    labels:
      traefik.enable: "{{ netdata_available_externally }}"
      traefik.http.routers.netdata.rule: "Host(`{{ netdata_hostname }}.{{ server_domain }}`)"
      traefik.http.routers.netdata.entrypoints: "websecure"
      traefik.http.routers.netdata.middlewares: "authelia@docker"

      traefik.http.routers.netdata.tls.certresolver: "letsencrypt"
      traefik.http.routers.netdata.tls.domains[0].main: "{{ server_domain }}"
      traefik.http.routers.netdata.tls.domains[0].sans: "*.{{ server_domain }}"

      traefik.http.services.netdata.loadbalancer.server.port: "19999"
