- name: Install Samba packages
  package:
    name: "{{ samba_packages }}"
    state: present

- name: Create Samba shares root directory (if not exists)
  file:
    state: directory
    path: "{{ samba_shares_root }}"
    owner: root
    group: root
    mode: "0755"

- name: Create Samba users if they don't exist
  shell: >
    set -o nounset -o pipefail -o errexit &&
    (pdbedit --user={{ item.name }} 2>&1 > /dev/null) \
    || (echo {{ item.smbpasswd }}; echo {{ item.smbpasswd }}) \
    | smbpasswd -s -a {{ item.name }}
  args:
    executable: /bin/bash
  with_items: "{{ samba_users }}"
  register: create_user_output
  changed_when: "'Added user' in create_user_output.stdout"

- name: Configuring samba shares
  template:
    src: config_smb.conf
    dest: /etc/samba/smb.conf
    owner: root
    group: root
    mode: 0644
    validate: 'testparm -s %s'
  notify:
    - Restart Samba services # Handler
