---
radarr_enabled: false
radarr_available_externally: "false"

# directories
radarr_movies_directory: "{{ movies_root }}"
radarr_download_directory: "{{ downloads_root }}"

radarr_volume: "{{ docker_volume }}/radarr" # tank/docker/radarr
radarr_mountpoint: "{{ docker_mountpoint }}/radarr" # /data/docker/radarr

# uid / gid
radarr_user_id: "0"
radarr_group_id: "0"

# network
radarr_port: "7878"
radarr_hostname: "radarr"

# specs
radarr_memory: 1g
