---
nzbget_enabled: false
nzbget_available_externally: "false"

# directories

nzbget_volume: "{{ docker_volume }}/nzbget" # dozer/docker/nzbget
nzbget_mountpoint: "{{ docker_mountpoint }}/nzbget" # /data/docker/nzbget
nzbget_download_directory: "{{ downloads_root }}"

# uid / gid
nzbget_user_id: "0"
nzbget_group_id: "0"

# network
nzbget_port: "6789"
nzbget_hostname: "nzbget"

# specs
nzbget_memory: "1g"
