---
portainer_enabled: false
portainer_available_externally: "false"

# directories
portainer_volume: "{{ docker_volume }}/portainer" # dozer/docker/portainer
portainer_mountpoint: "{{ docker_mountpoint }}/portainer" # /data/docker/portainer
portainer_data_directory: "{{ portainer_mountpoint }}/config"

# network
portainer_port: "9000"
portainer_hostname: "portainer"

# specs
portainer_memory: 1g
