---
# External Access :
traefik_enabled: false

# directories
traefik_volume: "{{ docker_volume }}/traefik" # dozer/docker/traefik
traefik_mountpoint: "{{ docker_mountpoint }}/traefik" # /data/docker/traefik

# network
traefik_port_http: "80"
traefik_port_https: "443"
traefik_port_ui: "8083"

traefik_docker_image: traefik:v2.6
traefik_log_level: "DEBUG"

## infos: https://go-acme.github.io/lego/dns/
traefik_dns_provider: cloudflare
traefik_environment_variables:
  CF_DNS_API_TOKEN: "abcdabcd123412341234"

## certificates
# traefik_acme_server: "https://acme-staging-v02.api.letsencrypt.org/directory" # staging
traefik_acme_server: "https://acme-v02.api.letsencrypt.org/directory" # production

# specs
traefik_memory: 1g
