---
samba_packages:
  - samba
  - samba-vfs-modules


samba_shares_root: /data
samba_shares_group: ananas

media_share_path: "{{ medias_root }}"
downloads_share_path: "{{ downloads_root }}"
docker_share_path: "{{ docker_home }}"

samba_users:
  - {name: 'ananas', groups: 'ananas', smbpasswd: 'password'}
