---
- name: Create filesystem for Cloudflare DDNS
  community.general.zfs:
    name: "{{ cloudflare_volume }}"
    state: present
    extra_zfs_properties:
      mountpoint: "{{ cloudflare_mountpoint }}"

- name: Template Cloudflare Dynamic DNS config.yml with scoped token
  template:
    src: config.yml
    dest: "{{ cloudflare_mountpoint }}/config.yml"
  register: template_files_result


- name: Cloudflare Dynamic DNS Container
  docker_container:
    name: cloudflare-ddns
    image: joshava/cloudflare-ddns:latest
    pull: true
    hostname: cloudflare-ddns
    networks:
      - name: "{{ custom_network_name }}"
        aliases:
          - cloudflare-ddns
    network_mode: "{{ custom_network_name }}"
    networks_cli_compatible: yes
    volumes:
      - "{{ cloudflare_mountpoint }}/config.yml:/app/config.yaml"
    restart_policy: unless-stopped
    memory: "{{ cloudflare_memory }}"
    memory_swap: "{{ cloudflare_swap }}"
    # recreate: "{{ template_files_result is changed }}"
    recreate: "{{ recreate_containers }}"
