---
- name: Create Radarr Directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ radarr_data_directory }}"

- name: Radarr
  docker_container:
    name: radarr
    image: linuxserver/radarr
    pull: true
    volumes:
      - "{{ radarr_movies_directory }}:/movies:rw"
      - "{{ radarr_download_directory }}:/downloads:rw"
      - "{{ radarr_data_directory }}:/config:rw"
    ports:
      - "{{ radarr_port }}:7878"
    env:
      TZ: "{{ server_timezone }}"
      PUID: "{{ radarr_user_id }}"
      PGID: "{{ radarr_group_id }}"
    restart_policy: unless-stopped
    memory: "{{ radarr_memory }}"
    labels:
      traefik.enable: "{{ radarr_available_externally }}"
      traefik.http.routers.radarr.rule: "Host(`{{ radarr_hostname }}.{{ server_domain }}`)"
      traefik.http.routers.radarr.tls.certresolver: "letsencrypt"
      traefik.http.routers.radarr.tls.domains[0].main: "{{ server_domain }}"
      traefik.http.routers.radarr.tls.domains[0].sans: "*.{{ server_domain }}"
      traefik.http.routers.radarr.middlewares: "{{ radarr_middleware_chain }}"
      traefik.http.services.radarr.loadbalancer.server.port: "7878"
