---
- name: Create filesystem for Radarr
  community.general.zfs:
    name: "{{ radarr_volume }}"
    state: present
    extra_zfs_properties:
      mountpoint: "{{ radarr_mountpoint }}"

- name: Radarr
  docker_container:
    name: radarr
    image: linuxserver/radarr
    hostname: radarr
    pull: true
    networks:
      - name: "{{ custom_network_name }}"
        aliases:
          - radarr
    network_mode: "{{ custom_network_name }}"
    networks_cli_compatible: yes
    volumes:
      - "{{ radarr_movies_directory }}:/movies:rw"
      - "{{ radarr_download_directory }}:/downloads:rw"
      - "{{ radarr_mountpoint }}:/config:rw"
    ports:
      - "{{ radarr_port }}:7878"
    env:
      TZ: "{{ server_timezone }}"
      PUID: "{{ radarr_user_id }}"
      PGID: "{{ radarr_group_id }}"
    restart_policy: unless-stopped
    memory: "{{ radarr_memory }}"
    memory_swap: "{{ radarr_swap }}"
    labels:
      traefik.enable: "{{ radarr_available_externally }}"
      traefik.http.routers.radarr.rule: "Host(`{{ radarr_hostname }}.{{ server_domain }}`)"
      traefik.http.routers.radarr.entrypoints: "websecure"
      traefik.http.routers.radarr.tls.certresolver: "cloudflare"
      traefik.http.routers.radarr.tls.domains[0].main: "*.{{ server_domain }}"
      traefik.http.routers.radarr.tls.domains[0].sans: "{{ server_domain }}"
      traefik.http.routers.radarr.middlewares: "chain-authelia@file"
      traefik.http.services.radarr.loadbalancer.server.port: "{{ radarr_port }}"
