authelia_secret: "SECRET_KEY_HERE"

# authelia_sub_domain: "authelia"
# server_domain: "example.com"

duo_api_hostname: "DUO_HOSTNAME_HERE"
duo_api_integration_key: "INTEGRATION_KEY_HERE"
duo_api_secret_key: "SECRET_KEY_HERE"

session_authelia_secret: "SESSION_SECRET_KEY_HERE"

# storage_encryption_key: "STORAGE_ENCRYPTION_KEY_HERE"
storage_encryption_key: "7Vp8LW2QV9dtW62bC2yeFvu2Tdhgc7"



authelia_config_directory: "{{ docker_home }}/authelia"

authelia_admin_user:
  {
    name: "admin",
    displayname: "Admin",
    hashed_password: "admin",
    email: "admin@admin.com",
  }

authelia_user:
  {
    name: "user",
    displayname: "user",
    hashed_password: "user",
    email: "user@user.com",
  }


# uid / gid
authelia_user_id: "0"
authelia_group_id: "0"

# # error logging
authelia_log_level: "error"

# # network
authelia_port: "9091"
authelia_hostname: "login" # acces authelia portal from login.example.com
# default url redirection when accessed direclty via login.example.com :
authelia_redirection_url: "https://heimdall.{{ server_domain }}"

authelia_timezone: "{{ server_timezone }}"

# # specs
authelia_memory: 1g
