- name: Docker Socket Proxy Container
  docker_container:
    name: socket-proxy
    image: tecnativa/docker-socket-proxy:latest
    pull: true
    hostname: socket-proxy
    networks:
      - name: traefik_network
        aliases:
          - socket-proxy
    network_mode: traefik_network
    networks_cli_compatible: yes
    ports:
      - "2375:2375"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    env:
      NETWORKS: "1"
      SERVICES: "1"
      TASKS: "1"
      CONTAINERS: "1"
    restart_policy: unless-stopped
