###############################################################
#                   Authelia configuration                    #
###############################################################

host: 0.0.0.0
port: 9091
log_level: "{{ authelia_log_level }}"

# This secret can also be set using the env variables AUTHELIA_JWT_SECRET_FILE
# site to generate the secret: https://www.grc.com/passwords.htm
jwt_secret: "{{ authelia_secret }}" # comment to use docker secret file instead AUTHELIA_JWT_SECRET_FILE

# https://docs.authelia.com/configuration/miscellaneous.html#default-redirection-url
default_redirection_url: "{{ authelia_redirection_url }}"

totp:
  issuer: authelia.com
  period: 30
  skew: 1

# Enable the following for Duo Push Notification support
# https://www.authelia.com/docs/features/2fa/push-notifications.html
duo_api:
  hostname: "{{ duo_api_hostname }}"
  integration_key: "{{ duo_api_integration_key }}"
  # This secret can also be set using the env variables AUTHELIA_DUO_API_SECRET_KEY_FILE
  secret_key: "{{ duo_api_secret_key }}" # Comment to use docker secret file instead AUTHELIA_DUO_API_SECRET_KEY_FILE

authentication_backend:
  file:
    path: /config/users_database.yml
    # customize passwords based on https://docs.authelia.com/configuration/authentication/file.html
    password:
      algorithm: argon2id
      iterations: 1
      salt_length: 16
      parallelism: 8
      memory: 128 # blocks this much of the RAM. Tune this.

# https://docs.authelia.com/configuration/access-control.html
access_control:
  default_policy: bypass
  rules:
    # Rules applied to everyone
    - domain: "login.{{ server_domain }}"
      policy: bypass
    - domain:
      - heimdall.{{server_domain}}
      - traefik.{{server_domain}}
      - portainer.{{server_domain}}
      - qbittorrent.{{server_domain}}
      - nzbget.{{server_domain}}
      - sonarr.{{server_domain}}
      - radarr.{{server_domain}}
      - netdata.{{server_domain}}
      policy: two_factor
      subject:
      - "user:{{ authelia_admin_user.name }}"
      - "group:ananas"
    #   networks:
    #     - 192.168.1.0/24
    # - domain: "{{server_domain}}"
    #   policy: two_factor
    #   subject: "group:ananas"
    #   networks:
    #     - 192.168.1.0/24

session:
  name: authelia_session
  # This secret can also be set using the env variables AUTHELIA_SESSION_SECRET_FILE
  # Used a different secret, but the same site as jwt_secret above.
  secret: "{{ session_authelia_secret }}" # comment to use docker secret file instead AUTHELIA_SESSION_SECRET_FILE
  expiration: 3600 # 1 hour
  inactivity: 300 # 5 minutes
  domain: "{{ server_domain }}" # Should match whatever your root protected domain is

# Optional. Can improve performance on a busy system. If not enabled, session info is stored in memory.
#  redis:
#    host: redis
#    port: 6379
# This secret can also be set using the env variables AUTHELIA_SESSION_REDIS_PASSWORD_FILE
# password: authelia

regulation:
  max_retries: 3
  find_time: 120
  ban_time: 300

storage:
  # For local storage, uncomment lines below and comment out mysql. https://docs.authelia.com/configuration/storage/sqlite.html
   local:
     path: /config/db.sqlite3
  # mysql:
  #   # MySQL allows running multiple authelia instances. Create database and enter details below.
  #   host: MYSQL_HOST
  #   port: 3306
  #   database: authelia
  #   username: DBUSERNAME
  #   # Password can also be set using a secret: https://docs.authelia.com/configuration/secrets.html
  #   # password: use docker secret file instead AUTHELIA_STORAGE_MYSQL_PASSWORD_FILE

notifier:
  # smtp:
  #   username: SMTP_USERNAME
  #   # This secret can also be set using the env variables AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE
  #   # password: # use docker secret file instead AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE
  #   host: SMTP_HOST
  #   port: 587 #465
  #   sender: SENDER_EMAIL
  # For testing purpose, notifications can be sent in a file. Be sure map the volume in docker-compose.
 filesystem:
   filename: /config/notification.txt
