zfs_main_name: tank
zfs_main_ashift: 12
zfs_main_disk1: '/dev/disk/by-id/scsi-123abc'
zfs_main_disk2: '/dev/disk/by-id/scsi-456def'

zfs_secondary_name: dozer
zfs_secondary_ashift: 9
zfs_secondary_disk1: '/dev/disk/by-id/scsi-789ghi'

zfs_mountpoint_root: /data
## Tank:
media_volume: "{{ zfs_main_name }}/media"
media_mountpoint: "{{ zfs_mountpoint_root }}/media"

docker_volume: "{{ zfs_main_name }}/docker"
docker_mountpoint: "{{ zfs_mountpoint_root }}/docker"

## Dozer:
downloads_root: "{{ zfs_mountpoint_root }}/downloads"

torrents_downloads_volume: "{{ zfs_secondary_name }}/torrents"
torrents_downloads_mountpoint: "{{ downloads_root }}/torrents"

newsgroups_downloads_volume: "{{ zfs_secondary_name }}/newsgroups"
newsgroups_downloads_mountpoint: "{{ downloads_root }}/newsgroups"
