---
- name: Create filesystem for Qbittorrent
  community.general.zfs:
    name: "{{ qbittorrent_volume }}"
    state: present
    extra_zfs_properties:
      mountpoint: "{{ qbittorrent_mountpoint }}"

- name: Create Qbittorrent Directories
  file:
    path: "{{ item }}"
    state: directory

  with_items:
    - "{{ qbittorrent_config_directory }}"
    - "{{ qbittorrent_download_directory }}"
    - "{{ qbittorrent_watch_directory }}"

- name: Qbittorrent Docker Container
  docker_container:
    name: qbittorrent
    image: linuxserver/qbittorrent
    pull: true
    volumes:
      - "{{ qbittorrent_config_directory }}:/config:rw"
      - "{{ qbittorrent_download_directory }}:/downloads:rw"
    ports:
      - "{{ qbittorrent_port }}:8585"
    hostname: qbittorrent
    networks:
      - name: "{{ custom_network_name }}"
        aliases:
          - qbittorrent
    network_mode: "{{ custom_network_name }}"
    networks_cli_compatible: yes
    env:
      TZ: "{{ qbittorrent_timezone }}"
      PUID: "{{ qbittorrent_user_id }}"
      PGID: "{{ qbittorrent_group_id }}"
      WEBUI_PORT: "{{ qbittorrent_port }}"
    restart_policy: unless-stopped
    memory: "{{ qbittorrent_memory }}"
    memory_swap: "{{ qbittorrent_swap }}"
    labels:
      traefik.enable: "{{ qbittorrent_available_externally }}"
      traefik.http.routers.qbittorrent.rule: "Host(`{{ qbittorrent_hostname }}.{{ server_domain }}`)"
      traefik.http.routers.qbittorrent.entrypoints: "websecure"
      traefik.http.routers.qbittorrent.tls.certresolver: "cloudflare"
      traefik.http.routers.qbittorrent.tls.domains[0].main: "*.{{ server_domain }}"
      traefik.http.routers.qbittorrent.tls.domains[0].sans: "{{ server_domain }}"
      traefik.http.routers.qbittorrent.middlewares: "chain-authelia@file"
      traefik.http.services.qbittorrent.loadbalancer.server.port: "{{ qbittorrent_port }}"
    recreate: "{{ recreate_containers }}"
