---
- name: Create Qbittorent Directories
  file:
    path: "{{ item }}"
    state: directory
    # mode: 0755
  with_items:
    - "{{ qbittorrent_config_directory }}"
    - "{{ qbittorrent_download_directory }}"
    - "{{ qbittorrent_watch_directory }}"

- name: qbittorrent Docker Container
  docker_container:
    name: qbittorrent
    image: linuxserver/qbittorrent
    pull: true
    volumes:
      - "{{ qbittorrent_config_directory }}:/config:rw"
      - "{{ qbittorrent_download_directory }}:/root/Downloads:rw"
    ports:
      - "{{ qbittorrent_port }}:8585"
      - "6881:6881"
    env:
      TZ: "{{ qbittorrent_timezone }}"
      PUID: "{{ qbittorrent_user_id }}"
      PGID: "{{ qbittorrent_group_id }}"
      WEBUI_PORT: "8585"
    restart_policy: unless-stopped
    memory: "{{ qbittorrent_memory }}"
    labels:
      traefik.enable: "{{ qbittorrent_available_externally }}"
      traefik.http.routers.qbittorrent.rule: "Host(`{{ qbittorrent_hostname }}.{{ server_domain }}`)"
      traefik.http.routers.qbittorrent.tls.certresolver: "letsencrypt"
      traefik.http.routers.qbittorrent.tls.domains[0].main: "{{ server_domain }}"
      traefik.http.routers.qbittorrent.tls.domains[0].sans: "*.{{ server_domain }}"
      traefik.http.services.qbittorrent.loadbalancer.server.port: "8585"
