---
auth:
  scopedToken: "{{ cloudflare_token }}"
domains:
  - name: "{{ cloudflare_host }}"
    type: "{{ cloudflare_type }}"
    proxied: {{ cloudflare_proxy | bool }}
    create: true
    zoneName: "{{ cloudflare_zone }}"
  - name: "{{ cloudflare_zone_2 }}"
    type: "{{ cloudflare_type }}"
    proxied: {{ cloudflare_proxy | bool }}
    create: true
    zoneName: "{{ cloudflare_zone_2 }}"
