---
heimdall_enabled: true
heimdall_available_externally: "false"

# directories
heimdall_docker_image: linuxserver/heimdall:latest

heimdall_volume: "{{ docker_volume }}/heimdall" # dozer/docker/heimdall
heimdall_mountpoint: "{{ docker_mountpoint }}/heimdall" # /data/docker/heimdall

# network
heimdall_port_http: "10080"
heimdall_port_https: "10443"
heimdall_hostname: heimdall

# uid / gid
heimdall_user_id: "1310"
heimdall_group_id: "1310"

# specs
heimdall_memory: 1g
