---
- name: Create filesystem for Authelia
  community.general.zfs:
    name: "{{ authelia_volume }}"
    state: present
    extra_zfs_properties:
      mountpoint: "{{ authelia_mountpoint }}"

- name: Authelia Notification file
  file:
    path: "{{ authelia_mountpoint }}/notification.txt"
    state: touch

- name: Template Authelia configuration.yml
  template:
    src: configuration.yml
    dest: "{{ authelia_mountpoint }}/configuration.yml"
  register: authelia_config

- name: Authelia user_database
  template:
    src: users_database.yml
    dest: "{{ authelia_mountpoint }}/users_database.yml"

  # Authelia (Lite) - Self-Hosted Single Sign-On and Two-Factor Authentication
- name: Authelia Docker Container
  docker_container:
    name: authelia
    image: authelia/authelia:4.33
    pull: true
    hostname: authelia
    networks:
      - name: "{{ custom_network_name }}"
        aliases:
          - authelia
    network_mode: "{{ custom_network_name }}"
    networks_cli_compatible: yes
    volumes:
      - "{{ authelia_mountpoint }}:/config:rw"
    ports:
      - "{{ authelia_port }}:9091"
    env:
      TZ: "{{ authelia_timezone }}"
      PUID: "{{ authelia_user_id }}"
      PGID: "{{ authelia_group_id }}"
    restart_policy: unless-stopped
    memory: "{{ authelia_memory }}"
    labels:
      traefik.enable: "true" # External acces - default true
      traefik.http.routers.authelia.rule: "Host(`{{ authelia_hostname }}.{{ server_domain }}`)" # ex. Host(`login.example.com`)
      traefik.http.routers.authelia.entrypoints: "websecure"
      traefik.http.routers.authelia.tls.certresolver: "cloudflare"
      traefik.http.routers.authelia.tls.domains[0].main: "*.{{ server_domain }}"
      traefik.http.routers.authelia.tls.domains[0].sans: "{{ server_domain }}"
      traefik.http.services.authelia.loadbalancer.server.port: "9091"
    recreate: "{{ authelia_config is changed }}"
