---
- name: Create filesystem for NZBget
  community.general.zfs:
    name: "{{ nzbget_volume }}"
    state: present
    extra_zfs_properties:
      mountpoint: "{{ nzbget_mountpoint }}"

- name: NZBGet
  docker_container:
    name: nzbget
    image: linuxserver/nzbget
    hostname: nzbget
    networks:
      - name: "{{ custom_network_name }}"
        aliases:
          - nzbget
    network_mode: "{{ custom_network_name }}"
    networks_cli_compatible: yes
    pull: true
    volumes:
      - "{{ nzbget_download_directory }}:/downloads:rw"
      - "{{ nzbget_mountpoint }}:/config:rw"
    ports:
      - "{{ nzbget_port }}:6789"
    env:
      TZ: "{{ server_timezone }}"
      PUID: "{{ nzbget_user_id }}"
      PGID: "{{ nzbget_group_id }}"
    restart_policy: unless-stopped
    memory: "{{ nzbget_memory }}"
    memory_swap: "{{ nzbget_swap }}"
    labels:
      traefik.enable: "{{ nzbget_available_externally }}"
      traefik.http.routers.nzbget.rule: "Host(`{{ nzbget_hostname }}.{{ server_domain }}`)"
      traefik.http.routers.nzbget.entrypoints: "websecure"
      traefik.http.routers.nzbget.tls.certresolver: "cloudflare"
      traefik.http.routers.nzbget.tls.domains[0].main: "*.{{ server_domain }}"
      traefik.http.routers.nzbget.tls.domains[0].sans: "{{ server_domain }}"
      traefik.http.routers.nzbget.middlewares: "chain-authelia@file"
      traefik.http.services.nzbget.loadbalancer.server.port: "{{ nzbget_port }}"
    recreate: "{{ recreate_containers }}"
