---
- name: Create filesystem for Portainer
  community.general.zfs:
    name: "{{ portainer_volume }}"
    state: present
    extra_zfs_properties:
      mountpoint: "{{ portainer_mountpoint }}"
      atime: off
      compression: off

- name: Create Portainer Directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ portainer_data_directory }}"

- name: Portainer Docker Container
  docker_container:
    name: portainer
    image: portainer/portainer-ce:latest
    pull: true
    volumes:
      - "{{ portainer_data_directory }}:/data:rw"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/etc/timezone:/etc/timezone:ro"
    hostname: portainer
    networks:
      - name: "{{ custom_network_name }}"
        aliases:
          - portainer
    network_mode: "{{ custom_network_name }}"
    networks_cli_compatible: yes
    ports:
      - "{{ portainer_port }}:9000"
    restart_policy: unless-stopped
    memory: "{{ portainer_memory }}"
    labels:
      traefik.enable: "{{ portainer_available_externally }}"
      traefik.http.routers.portainer.rule: "Host(`{{ portainer_hostname }}.{{ server_domain }}`)"
      traefik.http.routers.portainer.entrypoints: "websecure"
      traefik.http.routers.portainer.tls.certresolver: "cloudflare"
      traefik.http.routers.portainer.tls.domains[0].main: "*.{{ server_domain }}"
      traefik.http.routers.portainer.tls.domains[0].sans: "{{ server_domain }}"
      traefik.http.routers.portainer.middlewares: "chain-authelia@file"
      traefik.http.services.portainer.loadbalancer.server.port: "9000"
