http:
  middlewares:
    chain-authelia:
      chain:
        middlewares:
          # - middlewares-rate-limit
          - middlewares-https-redirectscheme
          # - middlewares-secure-headers
          - middlewares-authelia
          # - middlewares-compress

    # chain-no-auth:
    #   chain:
    #     middlewares:
    #       - middlewares-rate-limit
    #       - middlewares-https-redirectscheme
    #       - middlewares-secure-headers
    #       - middlewares-compress
