---
sonarr_enabled: false
sonarr_available_externally: "false"

# directories
# sonarr_data_directory: "{{ sonarr_mountpoint }}/config"
sonarr_tv_directory: "{{ tvshows_root }}"
sonarr_download_directory: "{{ downloads_root }}"

sonarr_volume: "{{ docker_volume }}/sonarr" # dozer/docker/sonarr
sonarr_mountpoint: "{{ docker_mountpoint }}/sonarr" # /data/docker/sonarr

# uid / gid
sonarr_user_id: "0"
sonarr_group_id: "0"

# network
sonarr_port: "8989"
sonarr_hostname: "sonarr"

# specs
sonarr_memory: 1g
